In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv('eyetrack5.csv')   #编码默认UTF-8，若乱码自行更改

In [13]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(df[['eye_position1_up_x', 'eye_position1_up_y',
       'eye_position1_down_x', 'eye_position1_down_y', 'eye_position2_up_x',
       'eye_position2_up_y', 'eye_position2_down_x', 'eye_position2_down_y',
       'gaze_project_x', 'gaze_project_y', 'head_pitch', 'head_yaw',
       'head_roll', 'eye_center_position1_x', 'eye_center_position1_y',
       'eye_center_position2_x', 'eye_center_position2_y']])


StandardScaler()

In [14]:
X_train=scaler.transform(df[['eye_position1_up_x', 'eye_position1_up_y',
       'eye_position1_down_x', 'eye_position1_down_y', 'eye_position2_up_x',
       'eye_position2_up_y', 'eye_position2_down_x', 'eye_position2_down_y',
       'gaze_project_x', 'gaze_project_y', 'head_pitch', 'head_yaw',
       'head_roll', 'eye_center_position1_x', 'eye_center_position1_y',
       'eye_center_position2_x', 'eye_center_position2_y']])

In [15]:
X_train

array([[ 1.51295196, -0.35468522,  1.34222356, ...,  0.87159101,
        -2.35065019,  0.89644642],
       [ 1.50031967, -0.38326277,  1.35421841, ...,  0.02443713,
        -0.60195477, -0.84292723],
       [ 1.51295196, -0.38326277,  1.35421841, ..., -1.66987063,
        -1.47630248,  0.02675959],
       ...,
       [ 0.3002518 ,  2.36970764,  0.10675415, ...,  0.87159101,
         1.14674065,  0.89644642],
       [ 0.31288409,  2.37923349,  0.10675415, ...,  0.87159101,
         1.14674065,  0.89644642],
       [-4.19684464, -2.09791562, -4.42729863, ...,  0.87159101,
         1.14674065,  0.89644642]])

In [24]:
y_train=np.array(df['label'])

In [19]:
y_train

array([ 1,  1,  1, ..., 18, 18, 18], dtype=int64)

In [20]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

clf = SVC()
print(cross_val_score(clf, X_train, y_train, cv=10))

[0.30128205 0.39102564 0.32051282 0.3525641  0.37179487 0.30128205
 0.29487179 0.21794872 0.22435897 0.3525641 ]


In [26]:
sum([0.30128205, 0.39102564 ,0.32051282 ,0.3525641  ,0.37179487, 0.30128205
 ,0.29487179 ,0.21794872, 0.22435897 ,0.3525641 ])/10

0.312820511

In [21]:
clf.fit(X_train, y_train)

SVC()

In [22]:
predict=clf.predict(X_train)
from sklearn import  metrics

cm1 = metrics.confusion_matrix(y_train,predict)
print("Confusion matrix:\n%s" % cm1)

Confusion matrix:
[[79 12  0  0  0  0  4  6  0  0  0  0  2  3  0  0  0  0]
 [ 7 66  7  0  0  0  1  7  6  0  0  0  4  0  0  0  0  0]
 [ 0  1 61  6  0  0  0  6  4  9  0  0  0  0  8  0  1  4]
 [ 0  0 14 60  2  2  0  0  1  4  0  0  0  0  3  3  3  6]
 [ 0  0  0  9 49  8  0  0  0  4  6  3  0  0  0  2  0  3]
 [ 0  0  0  2 27 34  0  0  0  0  6  0  0  0  0  0  0  6]
 [25  0  0  0  0  0 54  0  0  0  0  0 10  1  0  0  0  0]
 [ 2 18  0  0  0  0  0 69  2  0  0  0  0  3  1  0  0  0]
 [ 0  0 16  4  0  0  0  0 51  6  0  1  0  1  9  1  0  0]
 [ 0  0  8 13  6  1  0  0  9 53  2  3  0  1  0  1  0  1]
 [ 0  0  0  5  2  4  0  0  1  6 52  2  0  0  0  1  1  6]
 [ 0  0  0  2  1  1  0  0  0  0 24 32  0  0  0  0  3  6]
 [ 6  1  0  0  0  0  8  4  0  0  0  0 55  1  0  0  0  0]
 [ 2  2  0  1  0  0  1 19  2  0  0  0  2 51  1  0  0  0]
 [ 1  0  4  2  0  0  0  1 14  0  0  0  0  4 50  8  0  0]
 [ 0  0  0  7  0  0  0  0 14 12  0  0  0  0  6 39  9  4]
 [ 0  0  0  2  0  2  0  0  0  7  7  0  0  0  0  0 33 24]
 [ 0  0  0  3

In [23]:
print("Accuracy={}".format(metrics.accuracy_score(y_train,predict)))

Accuracy=0.6025641025641025
